const option = {
  title: {
    text: '页面访问来源去向',
    textStyle: {
      fontSize: 16
    }
  },
  tooltip: {
    trigger: 'item',
    triggerOn: 'mousemove',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderWidth: 2,
    borderColor: '#999',
    textStyle: {
      color: '#000'
    },
    confine: true
  },
  series: [
    {
      type: 'sankey',
      layout: 'none',
      nodeAlign: 'left',
      data: [
        {
          name: '0.页面80',
          page_id: '80'
        }, {
          name: '0.页面91',
          page_id: '91'
        }, {
          name: '0.页面86',
          page_id: '86'
        }, {
          name: '0.页面98',
          page_id: '98'
        }, {
          name: '0.页面99',
          page_id: '99'
        }, {
          name: '0.其他',
          page_id: '0'
        }, {
          name: '1.游戏频道'
        }, {
          name: '2.页面115',
          page_id: '115',
          retain: 8524
        }, {
          name: '2.页面111',
          page_id: '111',
          retain: 7471
        }, {
          name: '2.页面102',
          page_id: '102',
          retain: 7462
        }, {
          name: '2.页面119',
          page_id: '119',
          retain: 7269
        }, {
          name: '2.页面117',
          page_id: '117',
          retain: 5198
        }, {
          name: '2.其他',
          page_id: '',
          retain: 7628
        }, {
          name: '3.页面200',
          page_id: '200',
          retain: 8818
        }, {
          name: '3.页面220',
          page_id: '220',
          retain: 8524
        }, {
          name: '3.页面201',
          page_id: '201',
          retain: 7471
        }, {
          name: '3.页面214',
          page_id: '214',
          retain: 7462
        }, {
          name: '3.页面203',
          page_id: '203',
          retain: 5198
        }, {
          name: '3.其他',
          page_id: '',
          retain: 6079
        }, {
          name: '4.页面309',
          page_id: '309'
        }, {
          name: '4.页面301',
          page_id: '301'
        }, {
          name: '4.页面313',
          page_id: '313'
        }, {
          name: '4.页面305',
          page_id: '305'
        }, {
          name: '4.页面306',
          page_id: '306'
        }, {
          name: '4.其他',
          page_id: ''
        }
      ],
      links: [{
        SOURCE_ID: '80',
        SOURCE: '0.页面80',
        TARGET_ID: '大首页',
        TARGET: '1.游戏频道',
        VV: 8524,
        page_id: '80',
        source: '0.页面80',
        target: '1.游戏频道',
        value: 8524
      }, {
        SOURCE_ID: '91',
        SOURCE: '0.页面91',
        TARGET_ID: '大首页',
        TARGET: '1.游戏频道',
        VV: 7471,
        page_id: '91',
        source: '0.页面91',
        target: '1.游戏频道',
        value: 7471
      }, {
        SOURCE_ID: '86',
        SOURCE: '0.页面86',
        TARGET_ID: '大首页',
        TARGET: '1.游戏频道',
        VV: 7462,
        page_id: '86',
        source: '0.页面86',
        target: '1.游戏频道',
        value: 7462
      }, {
        SOURCE_ID: '98',
        SOURCE: '0.页面98',
        TARGET_ID: '大首页',
        TARGET: '1.游戏频道',
        VV: 7269,
        page_id: '98',
        source: '0.页面98',
        target: '1.游戏频道',
        value: 7269
      }, {
        SOURCE_ID: '99',
        SOURCE: '0.页面99',
        TARGET_ID: '大首页',
        TARGET: '1.游戏频道',
        VV: 5198,
        page_id: '99',
        source: '0.页面99',
        target: '1.游戏频道',
        value: 5198
      }, {
        SOURCE_ID: '0',
        SOURCE: '0.其他',
        TARGET_ID: '大首页',
        TARGET: '1.游戏频道',
        VV: 7628,
        page_id: '0',
        source: '0.其他',
        target: '1.游戏频道',
        value: 7628
      }, {
        SOURCE_ID: '大首页',
        SOURCE: '1.游戏频道',
        TARGET_ID: '115',
        TARGET: '2.页面115',
        VV: 8524,
        page_id: '115',
        source: '1.游戏频道',
        target: '2.页面115',
        value: 8524
      }, {
        SOURCE_ID: '大首页',
        SOURCE: '1.游戏频道',
        TARGET_ID: '111',
        TARGET: '2.页面111',
        VV: 7471,
        page_id: '111',
        source: '1.游戏频道',
        target: '2.页面111',
        value: 7471
      }, {
        SOURCE_ID: '大首页',
        SOURCE: '1.游戏频道',
        TARGET_ID: '102',
        TARGET: '2.页面102',
        VV: 7462,
        page_id: '102',
        source: '1.游戏频道',
        target: '2.页面102',
        value: 7462
      }, {
        SOURCE_ID: '大首页',
        SOURCE: '1.游戏频道',
        TARGET_ID: '119',
        TARGET: '2.页面119',
        VV: 7269,
        page_id: '119',
        source: '1.游戏频道',
        target: '2.页面119',
        value: 7269
      }, {
        SOURCE_ID: '大首页',
        SOURCE: '1.游戏频道',
        TARGET_ID: '117',
        TARGET: '2.页面117',
        VV: 5198,
        page_id: '117',
        source: '1.游戏频道',
        target: '2.页面117',
        value: 5198
      }, {
        SOURCE_ID: '大首页',
        SOURCE: '1.游戏频道',
        TARGET_ID: 0,
        TARGET: '2.其他',
        VV: 7628,
        page_id: 0,
        source: '1.游戏频道',
        target: '2.其他',
        value: 7628
      }, {
        SOURCE_ID: '115',
        SOURCE: '2.页面115',
        TARGET_ID: '220',
        TARGET: '3.页面220',
        VV: 8524,
        page_id: '220',
        source: '2.页面115',
        target: '3.页面220',
        value: 8524
      }, {
        SOURCE_ID: '111',
        SOURCE: '2.页面111',
        TARGET_ID: '201',
        TARGET: '3.页面201',
        VV: 7471,
        page_id: '201',
        source: '2.页面111',
        target: '3.页面201',
        value: 7471
      }, {
        SOURCE_ID: '102',
        SOURCE: '2.页面102',
        TARGET_ID: '214',
        TARGET: '3.页面214',
        VV: 7462,
        page_id: '214',
        source: '2.页面102',
        target: '3.页面214',
        value: 7462
      }, {
        SOURCE_ID: '119',
        SOURCE: '2.页面119',
        TARGET_ID: '200',
        TARGET: '3.页面200',
        VV: 7269,
        page_id: '200',
        source: '2.页面119',
        target: '3.页面200',
        value: 7269
      }, {
        SOURCE_ID: '117',
        SOURCE: '2.页面117',
        TARGET_ID: '203',
        TARGET: '3.页面203',
        VV: 5198,
        page_id: '203',
        source: '2.页面117',
        target: '3.页面203',
        value: 5198
      }, {
        SOURCE_ID: 0,
        SOURCE: '2.其他',
        TARGET_ID: '200',
        TARGET: '3.页面200',
        VV: 1549,
        page_id: '200',
        source: '2.其他',
        target: '3.页面200',
        value: 1549
      }, {
        SOURCE_ID: 0,
        SOURCE: '2.其他',
        TARGET_ID: 0,
        TARGET: '3.其他',
        VV: 6079,
        page_id: 0,
        source: '2.其他',
        target: '3.其他',
        value: 6079
      }, {
        SOURCE_ID: '220',
        SOURCE: '3.页面220',
        TARGET_ID: '309',
        TARGET: '4.页面309',
        VV: 8524,
        page_id: '309',
        source: '3.页面220',
        target: '4.页面309',
        value: 8524
      }, {
        SOURCE_ID: '201',
        SOURCE: '3.页面201',
        TARGET_ID: '301',
        TARGET: '4.页面301',
        VV: 7471,
        page_id: '301',
        source: '3.页面201',
        target: '4.页面301',
        value: 7471
      }, {
        SOURCE_ID: '214',
        SOURCE: '3.页面214',
        TARGET_ID: '313',
        TARGET: '4.页面313',
        VV: 7462,
        page_id: '313',
        source: '3.页面214',
        target: '4.页面313',
        value: 7462
      }, {
        SOURCE_ID: '200',
        SOURCE: '3.页面200',
        TARGET_ID: '305',
        TARGET: '4.页面305',
        VV: 7269,
        page_id: '305',
        source: '3.页面200',
        target: '4.页面305',
        value: 7269
      }, {
        SOURCE_ID: '203',
        SOURCE: '3.页面203',
        TARGET_ID: 0,
        TARGET: '4.其他',
        VV: 5198,
        page_id: 0,
        source: '3.页面203',
        target: '4.其他',
        value: 5198
      }, {
        SOURCE_ID: '200',
        SOURCE: '3.页面200',
        TARGET_ID: 0,
        TARGET: '4.其他',
        VV: 1549,
        page_id: 0,
        source: '3.页面200',
        target: '4.其他',
        value: 1549
      }, {
        SOURCE_ID: 0,
        SOURCE: '3.其他',
        TARGET_ID: '306',
        TARGET: '4.页面306',
        VV: 6079,
        page_id: '306',
        source: '3.其他',
        target: '4.页面306',
        value: 6079
      }],
      nodeGap: 20,
      right: 20,
      left: 10,
      top: 30,
      bottom: 40,
      focusNodeAdjacency: 'allEdges',
      layoutIterations: 0,
      nodeWidth: 120,
      draggable: false,
      levels: [{
        depth: 0,
        itemStyle: {
          color: '#b3cde3'
        },
        lineStyle: {
          opacity: 0.4
        }
      }, {
        depth: 1,
        itemStyle: {
          color: '#cccc00'
        },
        lineStyle: {
          opacity: 0.4
        }
      }, {
        depth: 4,
        itemStyle: {
          color: '#cccccc'
        },
        lineStyle: {
          opacity: 0.4
        }
      }, {
        depth: 2,
        itemStyle: {
          color: '#91c7ae'
        },
        lineStyle: {
          opacity: 0.4
        }
      }, {
        depth: 3,
        itemStyle: {
          color: '#ccebc5'
        },
        lineStyle: {
          opacity: 0.4
        }
      }],
      itemStyle: {
        normal: {
          borderWidth: 1,
          borderColor: '#aaa'
        }
      },
      label: {
        normal: {
          align: 'center',
          verticalAlign: 'middle',
          position: ['50%', '50%'],
          fontSize: '12',
          color: '#333'
        }
      }
    }
  ]
}

export default option
